export const LOAD_CONTACTS_START = "LOAD_CONTACTS_START";
export const LOAD_CONTACTS_SUCCESS = "LOAD_CONTACTS_SUCCESS";
export const LOAD_CONTACTS_ERROR = "LOAD_CONTACTS_ERROR";

export const ADD_CONTACT_START = "ADD_CONTACT_START";
export const ADD_CONTACT_SUCCESS = "ADD_CONTACT_SUCCESS";
export const ADD_CONTACT_ERROR = "ADD_CONTACT_ERROR";

export const VIEW_CONTACT_START = "VIEW_CONTACT_START";
export const VIEW_CONTACT_SUCCESS = "VIEW_CONTACT_SUCCESS";
export const VIEW_CONTACT_ERROR = "VIEW_CONTACT_ERROR";

export const UPDATE_CONTACT_START = "UPDATE_CONTACT_START";
export const UPDATE_CONTACT_SUCCESS = "UPDATE_CONTACT_SUCCESS";
export const UPDATE_CONTACT_ERROR = "UPDATE_CONTACT_ERROR";

export const DELETE_CONTACT_START = "DELETE_CONTACT_START";
export const DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS";
export const DELETE_CONTACT_ERROR = "DELETE_CONTACT_ERROR";
